---
- name: execute newaliases
  shell: /usr/bin/newaliases
  args:
    chdir: /etc
    
- name: Reload the daemon
  systemd:
    daemon_reload: yes

- name: restart postfix
  service:
    name: postfix
    enabled: true
    state: restarted
    
- name: reload postfix
  service:
    name: postfix
    state: reloaded

- name: postmap mydomains
  shell: /usr/sbin/postmap /etc/postfix/mydomains
  args:
    chdir: /etc/postfix
