---
- name: execute newaliases
  shell: /usr/bin/newaliases
  args:
    chdir: /etc

- name: restart postfix
  service:
    name: postfix
    state: restarted

- name: reload postfix
  service:
    name: postfix
    state: reloaded

- name: postmap mydomains
  shell: /usr/sbin/postmap /etc/postfix/mydomains
  args:
    chdir: /etc/postfix

- name: postmap transport
  shell: /usr/sbin/postmap /etc/postfix/transport
  args:
    chdir: /etc/postfix
  notify:
    - restart postfix
