- name: Prepare
  hosts: all
  become: true
  gather_facts: yes
  tasks:
    - name: Update apt cache (debian)
      apt:
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: Update yum cache (redhat)
      yum:
        update_cache: true
      when: ansible_os_family == 'RedHat'

    - name: Make sure rsyslog is present (debian + redhat)
      package:
        name: rsyslog
        state: present

    - name: Make sure rsyslog is running (redhat)
      service:
        name: rsyslog
        state: started
      when: ansible_os_family == 'RedHat'

    - name: Make sure syslog is running (debian)
      service:
        name: syslog
        state: started
      when: ansible_os_family == 'Debian'

    - name: Install utilities that support the "verify" stage
      package:
        name:
          - net-tools
          - swaks
