---
- name: Check whether packages are installed
  hosts: all
  become: yes

  tasks:
    - name: Gather package facts
      package_facts:
        manager: auto

    - name: Verify Packages
      assert:
        that: "'{{ item }}' in ansible_facts.packages"
      with_items:
        - mailutils
      when: ansible_os_family == 'Debian'

    - name: Verify Packages
      assert:
        that: "'{{ item }}' in ansible_facts.packages"
      with_items:
        - mailutils
      when: ansible_os_family == 'Redhat'
